### ISSUE TITLE
Celebrate on error shows an HTML page with only object Object printed on console

### ISSUE THREAD

**Issue by abhishekp1996** [arb/celebrate#120]
- `node` version - 10.16.0
- `celebrate` version - 10.0.1
- `joi` version (via `npm ls --depth=0 | grep joi`) - 15.0.3

My `joi` schema looks like this:

`{email: Joi.string().trim().email()}`

Here is an example value that is not working as expected:

`a`

The issue I am having with `celebrate` is:

The issue is that whenever I hit the API, the validation kicks in and if the validation is failed, a HTML page is returned with nothing but `object Object` in the body and also in console the same thing is printed.

But when the validation format are correct, everything is working good.

What could be wrong?

**Comment by arb** [comment]
Are you using `errors()`? If so, yes, the response when a celebrate errors happens is going to be a JSON object which explains why you're seeing `object Object`. It is up to the consumer to display an HTML page formatted as you'd like if that's what you want.

If you're not using `errors()`, then you're likely seeing the default Express error handler and again, it responds with HTML rather than JSON.

**Comment by abhishekp1996** [comment]
@arb I was not using `errors()` and Express was picking up their default error handler. Actually there was error handler in place, but I was using only 3 parameters for error handler - `err`, `request`, `response`. When I added `next` the code started working correctly. Thank you! I am _celebrating_
