### ISSUE TITLE
Celebrate errors no longer extend `Error`

### ISSUE THREAD

**Issue by schmod** [arb/celebrate#138]
- `node` version - 10.x
- `celebrate` version - 10.0.1
- `joi` version (via `npm ls --depth=0 | grep joi`) - N/A

Celebrate 10.0.0 [changed](https://github.com/arb/celebrate/commit/2598055f4a7fd7452404856e65e71b4822246af3#diff-6d186b954a58d5bb740f73d84fe39073R34-R39) the structure and context of the error objects that Celebrate produces (ie. the `err` that Celebrate passes into `next(err)`).  

This change appears to have broken some 3rd-party error-logging middlewares (specifically [sentry](https://sentry.io)) that expect errors passed to `next()` to extend the built-in JS `Error` object.

Would it be possible for `format` to start returning an `Error` object with a sensible `message` property, instead of a plain object?

**Comment by arb** [comment]
Yeah I changed that because I didn't like mutation the result object, even if I was confident there wouldn't be a collision... 

Are there any other benefits of sub classing `Error` other than to work cleaner with some 3rd (4th in this case 😅) party libraries. POJOs are way easier to work with than Error objects plus Error objects are much heavier than `celebrate` really needs. Real `Error`s include things like stack traces which I don't need.

**Comment by schmod** [comment]
What if we put a `message` property on the root-level Celebrate error? It seems like this could be a middle-ground that does the right thing for many logging/error-handling middlewares that expect "error-like" objects to be passed to `next(err)`.

Sentry still wouldn't currently handle this correctly, but I could open an issue with them to see if they'd be open to fixing that.

**Comment by arb** [comment]
@schmod how's [this](https://github.com/arb/celebrate/pull/144) look to you?
