### ISSUE TITLE
Adjust Engine Value

### ISSUE THREAD

**Issue by arb** [arb/celebrate#169]
Joi only tests against 12 and "node" so I should update accordingly.

**Comment by izolate** [comment]
Hi @arb - I understand the reasoning behind this change, but unfortunately this prevents the use of celebrate in Google Cloud Functions (GCF). The latest supported runtime on GCF is Node v10, so celebrate now refuses to install due to the `engine` version limitation.

Perhaps you could consider dropping it back to v10 until GCF supports a more recent runtime? Otherwise the workaround is to use `celebrate@12.0.1`

**Comment by arb** [comment]
Does GCF **require** an `engine` value? If not, I could just omit it entirely and leave it on the consumer to deal with it? Frankly, it's a huge pain to keep up-to-date anyway.

**Comment by izolate** [comment]
@arb No, the `engine` is not required and omitting it will allow the package to be installed on any Node version. That's a decision that I'll leave up to you.
