### ISSUE TITLE
Access req.body object when validating

### ISSUE THREAD

**Issue by benjamin-daniel** [arb/celebrate#202]
- `node: v12.10.0` - 
- `celebrate: 12.1.0` - 
- `joi: 17.1.1` -

My `joi` schema looks like this:

```
import phone from 'phone'

const phoneMethodValidator = (value, helpers) => {
//  I need to get the value for the countryCode in req.body
  let values = phone(value, "NGA");
  if (values.length !== 2) {
    throw new Error("phone isn't valid");
  }
  return value;
};
`
`[Segments.BODY]: Joi.object().keys({
      countryCode: Joi.string().allow(null),
      phone: Joi.string()
        .custom(phoneMethodValidator, "phone validation")
        .required()
})
```

Here is an example value that is not working as expected:

`
{phone: "08000000000", countryCode: "NGA" }
`

The issue I am having with `celebrate` is: I need access to the value of countryCode in req.body, and Joi.ref isn't doing any justice

I need the value of countryCode so I can use it to do custom validation of the phone number provided. Thanks

**Comment by arb** [comment]
Trying taking a look at [this test](https://github.com/arb/celebrate/blob/master/test/celebrate.test.js#L332-L343) that uses the request context during validation. That might help you achieve what you're trying to do. I'm not 100% sure though since the `.custom` method is a little limited with what all it's going to received. Make sure you check out everything available in `helpers` to see if there is anything useful there.

**Comment by benjamin-daniel** [comment]
Thanks but looking into helpers helped a lot(got help from a friend). 

```
helpers.state.ancestors[0] // gives the full object
```
